[SERVICE]
    Flush 5
    Log_Level info
    Parsers_File /fluent-bit/etc/parsers.conf
    HTTP_Server On
    HTTP_Listen 0.0.0.0
    HTTP_Port 2020
    Health_Check On
    storage.path /buffers/chunks
    storage.sync normal
    storage.checksum on
    storage.backlog.mem_limit 32M

[INPUT]
    Name tail
    Tag docker.*
    Path /var/lib/docker/containers/*/*-json.log
    Parser docker
    DB /buffers/tail.db
    Read_from_Head Off
    Refresh_Interval 10
    Rotate_Wait 30
    Mem_Buf_Limit 32M
    Skip_Long_Lines On
    storage.type filesystem

[OUTPUT]
    Name loki
    Match docker.*
    Host cortex-loki
    Port 3100
    Labels job=cortex-containers
    Line_Format json
    Retry_Limit False
    storage.total_limit_size 1G
